name: Build and deploy Aseprite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-version:
    name: Check latest Aseprite version
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.version_info.outputs.download_url }}
      latest_tag: ${{ steps.version_info.outputs.latest_tag }}
      should_build: ${{ steps.should_build.outputs.should_build }}
    steps:
      - name: Get latest Aseprite release info
        id: version_info
        run: |
          data=$(curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest)
          LATEST_TAG=$(echo "${data}" | jq -r '.tag_name')
          SOURCE_URL=$(echo "${data}" | jq -r '.assets[] | select(.name | test("Aseprite-.*-Source.zip")) | .browser_download_url')
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "download_url=${SOURCE_URL}" >> $GITHUB_OUTPUT

      - name: Load cached version
        id: cached_version
        uses: actions/cache@v4
        with:
          path: aseprite_version.txt
          key: aseprite-version-${{ steps.version_info.outputs.latest_tag }}

      - name: Should build?
        id: should_build
        run: |
          if [ "${{ steps.cached_version.outputs.cache-hit }}" == "true" ]; then
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

  build-aseprite:
    name: Build Aseprite
    needs: check-version
    if: ${{ needs.check-version.outputs.should_build == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: choco install ninja cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Download Skia
        run: |
          $skiaUrl = "https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip"
          Invoke-WebRequest -Uri $skiaUrl -OutFile skia.zip
          Expand-Archive skia.zip -DestinationPath skia

      - name: Download Aseprite source
        run: |
          Invoke-WebRequest -Uri "${{ needs.check-version.outputs.download_url }}" -OutFile aseprite.zip
          Expand-Archive aseprite.zip -DestinationPath aseprite

      - name: Compile Aseprite
        run: |
          cd aseprite
          mkdir build
          cd build
          cmake `
            -DCMAKE_BUILD_TYPE=Release `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR="$env:GITHUB_WORKSPACE\skia" `
            -DSKIA_LIBRARY_DIR="$env:GITHUB_WORKSPACE\skia\out\Release-x64" `
            -DSKIA_LIBRARY="$env:GITHUB_WORKSPACE\skia\out\Release-x64\skia.lib" `
            -G Ninja `
            ..
          ninja aseprite

      - name: Create zip
        run: |
          mkdir aseprite_release
          cp aseprite/build/bin/aseprite.exe aseprite_release/
          cp -r aseprite/build/bin/data aseprite_release/
          Compress-Archive -Path aseprite_release/* -DestinationPath Aseprite-${{ needs.check-version.outputs.latest_tag }}-Windows.zip

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.latest_tag }}
          name: Aseprite ${{ needs.check-version.outputs.latest_tag }}
          draft: true
          files: Aseprite-${{ needs.check-version.outputs.latest_tag }}-Windows.zip

      - name: Cache version
        uses: actions/cache@v4
        with:
          path: aseprite_version.txt
          key: aseprite-version-${{ needs.check-version.outputs.latest_tag }}
